name = "Biot"
uuid = "403ec0fe-bfd5-4107-9e65-d62221e24dd0"
authors = ["Eli Mattingly"]
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[compat]
Interpolations = "0.13.5"
PyPlot = "2.10.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
